image:
  tag: user-api-1.3.0
ingress:
  enabled: true
  className: nginx
  host: dev.dracolich.app
  path: /dracolich/user/api/v0
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
    - hosts:
        - dev.dracolich.app
      secretName: dev-dracolich-app-tls
