image:
  tag: user-api-latest

ingress:
  enabled: true
  className: nginx
  host: dev.dracolich.cc
  path: /dracolich-user/api/v0
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
    - hosts:
        - dev.dracolich.cc
      secretName: dev-dracolich-cc-tls
